In [16]:
import numpy as np
import pandas as pd

In [17]:
df=pd.DataFrame({'Text':['people watch youtube','youtube watch youtube',
'people write comments','youtube write comments'],'output':[1,1,0,0]})
df

Text  output
0    people watch youtube       1
1   youtube watch youtube       1
2   people write comments       0
3  youtube write comments       0

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer(ngram_range=(3,3))
#bag of words
bow=vect.fit_transform(df['Text'])

In [25]:
print(vect.vocabulary_)
sorted(vect.vocabulary_.items())

{'people watch youtube': 0, 'youtube watch youtube': 2, 'people write comments': 1, 'youtube write comments': 3}


[('people watch youtube', 0),
 ('people write comments', 1),
 ('youtube watch youtube', 2),
 ('youtube write comments', 3)]

In [26]:
print(bow.toarray())

[[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect=TfidfVectorizer()
tfidf=tfidf_vect.fit_transform(df['Text'])
tfidf_vect.fit_transform(df['Text']).toarray()
#tf=frequency of word in document/ total words in document
#idf=log(total documents/ documents with word in it) + 1


array([[0.        , 0.61366674, 0.61366674, 0.        , 0.49681612],
       [0.        , 0.        , 0.52546357, 0.        , 0.8508161 ],
       [0.57735027, 0.57735027, 0.        , 0.57735027, 0.        ],
       [0.61366674, 0.        , 0.        , 0.61366674, 0.49681612]])